export type Lang = "id" | "en";

const idContent = {
  meta: {
    title: "Kayla — Software Engineering & IT",
    description:
      "Portofolio Ratu Balqis Kayla Lutfian Habilah — Software Engineering & IT (Rekayasa Perangkat Lunak).",
  },
  nav: {
    brand: "KAYLA",
    toggleTheme: "Ganti mode terang/gelap",
    menu: "Buka menu",
    close: "Tutup menu",
    language: "Pilih bahasa",
    links: [
      { id: "home", label: "Beranda" },
      { id: "skills", label: "Keahlian" },
      { id: "experience", label: "Pengalaman" },
      { id: "projects", label: "Proyek" },
      { id: "resume", label: "Resume" },
      { id: "contact", label: "Kontak" },
    ],
  },
  hero: {
    badge: "TERSEDIA UNTUK BEKERJA",
    nameL1: "RATU BALQIS",
    nameL2: "KAYLA LUTFIAN HABILAH",
    role: "REKAYASA PERANGKAT LUNAK (SOFTWARE ENGINEERING & IT)",
    tagline:
      "Siswa jurusan Rekayasa Perangkat Lunak dengan fokus pada pengembangan web, pemrosesan logika sistem, dan pengelolaan basis data. Memiliki ketelitian tinggi dalam pengerjaan teknis serta kemampuan komunikasi yang kuat. Berharap dapat memberikan kontribusi positif, menerapkan keahlian IT/programming, serta berkembang lebih jauh bersama perusahaan.",
    ctaProjects: "LIHAT PROYEK",
    ctaResume: "RESUME",
    ctaContact: "HUBUNGI SAYA",
    avatarLabel: "PROFILE",
    cardBadge: "FULLSTACK DEVELOPER",
    photoSrc: "/images/profil.jpg",
    photoAlt: "Foto Ratu Balqis Kayla Lutfian Habilah",
    motto: "Ketenangan pikiran lebih berharga daripada kehadiran yang dipaksakan!",
  },
  marquee: [
    "PHP",
    "JAVASCRIPT",
    "NODE.JS",
    "NEXT.JS",
    "TAILWIND CSS",
    "MYSQL",
    "GIT & GITHUB",
    "VS CODE",
    "OPENAI",
    "GEMINI",
    "CODE",
    "AI ASSISTANTS",
  ],
  stats: {
    kicker: "01 // KEAHLIAN",
    title: "KEAHLIAN & TEKNOLOGI",
    subtitle: "Toolkit, hard skills & soft skills",
    equipmentTitle: "TOOLKIT LOG",
    equipmentTag: "HARD SKILLS",
    categories: [
      {
        name: "Administrative & Productivity Tools",
        items: [
          "Microsoft Word",
          "Microsoft Excel",
          "Google Spreadsheet",
          "Adobe Illustrator",
          "Canva",
          "CapCut",
        ],
      },
      {
        name: "Technical & Data Tools (Program & Basis Data)",
        items: [
          "Flutter",
          "Dart",
          "PHP",
          "JavaScript",
          "Node.js",
          "Next.js",
          "Tailwind CSS",
          "MySQL",
          "Visual Studio Code",
          "Git",
          "GitHub",
        ],
      },
      {
        name: "AI & Automation Assistants",
        items: ["OpenAI", "Gemini", "Google Stitch", "Freebuf", "Qwen", "Codex"],
      },
    ],
    traitsTitle: "SOFT SKILLS & CAPABILITIES",
    traitsSub: "BONUS STATS",
    traits: [
      {
        name: "Public Speaking & Presentasi",
        desc: "Mampu menyampaikan ide, materi, dan presentasi teknis secara jelas serta percaya diri di hadapan audiens luas.",
        stat: 75,
      },
      {
        name: "Komunikasi Efektif & Empati Layanan",
        desc: "Ramah, jelas, dan berorientasi pada kebutuhan pengguna.",
        stat: 85,
      },
      {
        name: "Ketelitian & Kerapian",
        desc: "Detail-oriented dalam setiap pencatatan, pengujian kode, dan validasi data.",
        stat: 80,
      },
      {
        name: "Kerja Sama Tim & Koordinasi Interpersonal",
        desc: "Kolaboratif dalam organisasi, alur kerja proyek, dan pertunjukan publik.",
        stat: 80,
      },
      {
        name: "Manajemen Waktu & Adaptabilitas",
        desc: "Cepat beradaptasi dengan alat, teknologi, dan lingkungan baru.",
        stat: 90,
      },
    ],
    buffsTitle: "ACTIVE BUFFS",
    buffs: ["+20% Ketelitian", "+15% Komunikasi", "+25% Adaptabilitas"],
  },
  projects: {
    kicker: "03 // PROYEK",
    title: "PROJECT PORTFOLIO",
    subtitle: "Proyek full-stack & studi kasus",
    cta: "BUKA APLIKASI",
    sourceCta: "GITHUB",
    galleryCta: "LIHAT GALERI FOTO",
    prev: "Sebelumnya",
    next: "Berikutnya",
    close: "Tutup",
    galleryLabel: "Foto",
    featuredLabel: "⭐ PROYEK UNGGULAN",
    items: [
      {
        title: "Quote of the Day App (QOTD)",
        desc: "Aplikasi web penyedia kutipan harian interaktif dan responsif yang menampilkan inspirasi secara dinamis. Dilengkapi dengan fitur pembaruan kutipan real-time, integrasi API/data fetching, serta antarmuka modern yang dikembangkan menggunakan Flutter Web untuk performa yang optimal di berbagai perangkat (desktop & mobile).",
        tech: [
          "Flutter Web / Dart",
          "Rest API / JSON Integration",
          "HTML5 / CSS3",
          "VS Code",
        ],
        thumb: "/images/quote1.png",
        gallery: [
          "/images/quote1.png",
          "/images/quote2.png",
          "/images/quote3.png",
          "/images/quote4.png",
          "/images/quote5.png",
        ],
        alt: "Tampilan aplikasi Quote of the Day App (QOTD)",
        url: "https://quote-day.netlify.app",
        repo: "https://github.com/nikellaa08/QuoteOfTheDay-Kayla.git",
        featured: true,
        noLinks: false,
      },
      {
        title: "Kuis Interaktif",
        desc: "Aplikasi web kuis edukatif berbasis logika interaktif dengan sistem penilaian waktu nyata, gamifikasi streak, mekanisme remedial real-time, serta pembahasan materi edukatif yang dibungkus dalam UI Frosted Glassmorphism yang elegan.",
        tech: ["Flutter Web / Dart", "PHP", "JavaScript", "MySQL", "Glassmorphism UI"],
        thumb: "/images/kuis1.png",
        gallery: [
          "/images/kuis1.png",
          "/images/kuis2.png",
          "/images/kuis3.png",
          "/images/kuis4.png",
          "/images/kuis5.png",
          "/images/kuis6.png",
          "/images/kuis7.png",
          "/images/kuis8.png",
        ],
        alt: "Tampilan aplikasi Kuis Interaktif",
        url: "https://kuis-intrktf.netlify.app",
        repo: "https://github.com/nikellaa08/Kuis-Kayla.git",
        featured: true,
        noLinks: false,
      },
      {
        title: "Sistem Absensi Siswa",
        desc: "Website absensi siswa berbasis web yang dirancang untuk membantu sekolah mengelola dan memantau kehadiran siswa secara digital. Sistem memiliki role Admin/Guru dan Siswa, absensi manual satu klik dengan deteksi keterlambatan, pengajuan izin dan sakit dengan unggahan surat pendukung, verifikasi oleh guru, riwayat kehadiran, serta dashboard monitoring absensi.",
        tech: [
          "Next.js",
          "React",
          "Node.js",
          "Tailwind CSS",
          "Local Storage",
          "FileReader API",
        ],
        thumb: "/images/absen1.png",
        gallery: [
          "/images/absen1.png",
          "/images/absen2.png",
          "/images/absen3.png",
          "/images/absen4.png",
          "/images/absen5.png",
        ],
        alt: "Tampilan aplikasi Sistem Absensi Siswa",
        url: "https://symphonious-basbousa-5b7956.netlify.app/",
        repo: "https://github.com/nikellaa08/AbsensiSiswa-Kayla.git",
        featured: false,
        noLinks: false,
      },
      {
        title: "Relawan Nusantara",
        desc: "Platform web koordinasi relawan interaktif yang dirancang untuk memudahkan pendaftaran, penjadwalan, dan pengelolaan kegiatan sosial, lingkungan, serta pendidikan secara terpadu.",
        tech: ["Node.js", "Express", "JavaScript", "MySQL"],
        thumb: "/images/relawan.png",
        gallery: ["/images/relawan.png"],
        alt: "Tampilan platform Relawan Nusantara",
        url: "",
        repo: "",
        featured: false,
        noLinks: true,
      },
    ],
  },
  experience: {
    kicker: "02 // EXP LOG",
    title: "ADVENTURE LOG",
    subtitle: "Pengalaman & rekam jejak",
    entries: [
      {
        tag: "Lv. 1 — EDUKASI",
        color: "yellow",
        title: "Pendidikan",
        desc: "",
        schools: [
          {
            name: "SMK Jakarta Pusat 1",
            period: "2024 – 2027",
            detail: "Jurusan Rekayasa Perangkat Lunak (RPL)",
          },
        ],
      },
      {
        tag: "Lv. 2 — PROJECT DEV",
        color: "blue",
        title: "Pengalaman Pengembangan Proyek Web & Aplikasi",
        desc: "Pengalaman praktis dalam merancang, membangun, dan menyempurnakan berbagai aplikasi web interaktif berbasis logika full-stack dan antarmuka modern.",
        subs: [
          {
            name: "Pengembang Utama — Quote of the Day App (QOTD)",
            desc: "Mengembangkan aplikasi web kutipan harian interaktif berbasis Flutter Web dengan pembaruan real-time dan data fetching API.",
          },
          {
            name: "Pengembang Utama — Kuis Interaktif",
            desc: "Merancang aplikasi kuis edukatif berbasis logika PHP, JavaScript, dan MySQL dengan UI Frosted Glassmorphism dan sistem penilaian real-time.",
          },
          {
            name: "Pengembang Full-Stack — Sistem Absensi Siswa",
            desc: "Membangun sistem manajemen kehadiran digital berbasis Next.js App Router dan Tailwind CSS dengan fitur verifikasi guru, deteksi keterlambatan, dan dashboard monitoring.",
          },
          {
            name: "Pengembang Full-Stack (Kolaborasi Tim) — Relawan Nusantara",
            desc: "Membangun platform web koordinasi relawan interaktif untuk kegiatan sosial, lingkungan, dan pendidikan menggunakan Node.js, Express, JavaScript, dan MySQL.",
          },
        ],
      },
      {
        tag: "Lv. 3 — ORGANISASI",
        color: "green",
        title: "Kegiatan Organisasi & Ekstrakurikuler",
        desc: "Pengalaman aktif di berbagai kegiatan non-akademik yang membentuk kerja sama tim dan keterampilan teknis.",
        subs: [
          {
            name: "Broadcasting",
            desc: "Pelatihan teknik pengambilan sudut foto dan video secara profesional.",
          },
          {
            name: "Teater, Hadroh, & Paduan Suara",
            desc: "Pengasahan keharmonisan kerja sama tim, ritme kerja, serta koordinasi antaranggota dalam pertunjukan publik.",
          },
        ],
      },
    ],
  },
  resume: {
    kicker: "RESUME",
    title: "PROFESSIONAL RESUME",
    subtitle: "Pratinjau CV & Dokumen Resmi",
    viewOnline: "VIEW ONLINE",
    download: "DOWNLOAD PDF",
    previewLabel: "RESUME PREVIEW",
    pdfHint: "PDF",
    previewFallback:
      "Pratinjau mungkin tidak tampil di sebagian perangkat — gunakan tombol 👁 VIEW ONLINE untuk membukanya di browser.",
    backLabel: "KEMBALI KE BERANDA",
  },
  contact: {
    kicker: "04 // CONTACT",
    title: "LET'S CONNECT",
    subtitle: "Siap membuka quest baru bersama Anda",
    note: "⚡ Respon cepat — balasan biasanya dalam 24 jam.",
    items: [
      {
        label: "EMAIL",
        value: "nikellaa08@gmail.com",
        href: "mailto:nikellaa08@gmail.com",
        emoji: "✉️",
        color: "yellow",
      },
      {
        label: "LINKEDIN",
        value: "linkedin.com/in/kayla-l-8b276b424",
        href: "https://www.linkedin.com/in/kayla-l-8b276b424",
        emoji: "💼",
        color: "blue",
      },
      {
        label: "WHATSAPP",
        value: "+62 857-7122-0340",
        href: "https://wa.me/6285771220340",
        emoji: "💬",
        color: "green",
      },
      {
        label: "GITHUB",
        value: "@nikellaa08",
        href: "https://github.com/nikellaa08",
        emoji: "🐙",
        color: "ink",
      },
    ],
    cvCta: "LIHAT RESUME",
    emailCta: "atau kirim email langsung",
  },
  footer: {
    text: "© 2026 Ratu Habibilah. Dibangun dengan Next.js & Tailwind CSS.",
  },
};

export type Content = typeof idContent;

const enContent: Content = {
  meta: {
    title: "Kayla — Software Engineering & IT",
    description:
      "Portfolio of Ratu Balqis Kayla Lutfian Habilah — Software Engineering & IT (Vocational Software Engineering).",
  },
  nav: {
    brand: "KAYLA",
    toggleTheme: "Toggle dark/light mode",
    menu: "Open menu",
    close: "Close menu",
    language: "Choose language",
    links: [
      { id: "home", label: "Home" },
      { id: "skills", label: "Skills" },
      { id: "experience", label: "Experience" },
      { id: "projects", label: "Projects" },
      { id: "resume", label: "Resume" },
      { id: "contact", label: "Contact" },
    ],
  },
  hero: {
    badge: "READY FOR WORK",
    nameL1: "RATU BALQIS",
    nameL2: "KAYLA LUTFIAN HABILAH",
    role: "SOFTWARE ENGINEERING & IT",
    tagline:
      "A Software Engineering student focused on web development, system logic processing, and database management. Highly meticulous in technical work with strong communication skills. Eager to contribute positively, apply IT/programming expertise, and grow further together with the company.",
    ctaProjects: "VIEW PROJECTS",
    ctaResume: "RESUME",
    ctaContact: "CONTACT ME",
    avatarLabel: "PROFILE",
    cardBadge: "FULLSTACK DEVELOPER",
    photoSrc: "/images/profil.jpg",
    photoAlt: "Photo of Ratu Balqis Kayla Lutfian Habilah",
    motto: "Peace of mind is worth more than a forced presence!"
  },
  marquee: [
    "PHP",
    "JAVASCRIPT",
    "NODE.JS",
    "NEXT.JS",
    "TAILWIND CSS",
    "MYSQL",
    "GIT & GITHUB",
    "VS CODE",
    "OPENAI",
    "GEMINI",
    "CODE",
    "AI ASSISTANTS",
  ],
  stats: {
    kicker: "01 // SKILLS",
    title: "SKILLS & TECHNOLOGIES",
    subtitle: "Toolkit, hard skills & soft skills",
    equipmentTitle: "TOOLKIT LOG",
    equipmentTag: "HARD SKILLS",
    categories: [
      {
        name: "Administrative & Productivity Tools",
        items: [
          "Microsoft Word",
          "Microsoft Excel",
          "Google Spreadsheet",
          "Adobe Illustrator",
          "Canva",
          "CapCut",
        ],
      },
      {
        name: "Technical & Data Tools (Program & Basis Data)",
        items: [
          "Flutter",
          "Dart",
          "PHP",
          "JavaScript",
          "Node.js",
          "Next.js",
          "Tailwind CSS",
          "MySQL",
          "Visual Studio Code",
          "Git",
          "GitHub",
        ],
      },
      {
        name: "AI & Automation Assistants",
        items: ["OpenAI", "Gemini", "Google Stitch", "Freebuf", "Qwen", "Codex"],
      },
    ],
    traitsTitle: "SOFT SKILLS & CAPABILITIES",
    traitsSub: "BONUS STATS",
    traits: [
      {
        name: "Public Speaking & Presentation",
        desc: "Able to deliver ideas, materials, and technical presentations clearly and confidently in front of a wide audience.",
        stat: 75,
      },
      {
        name: "Effective Communication & Service Empathy",
        desc: "Friendly, clear, and focused on user needs.",
        stat: 85,
      },
      {
        name: "Accuracy & Neatness",
        desc: "Detail-oriented in every record, code testing, and data validation.",
        stat: 80,
      },
      {
        name: "Teamwork & Interpersonal Coordination",
        desc: "Collaborative in organizations, project workflows, and public performances.",
        stat: 80,
      },
      {
        name: "Time Management & Adaptability",
        desc: "Quick to adapt to new tools, technologies, and environments.",
        stat: 90,
      },
    ],
    buffsTitle: "ACTIVE BUFFS",
    buffs: ["+20% Accuracy", "+15% Communication", "+25% Adaptability"],
  },
  projects: {
    kicker: "03 // PROJECTS",
    title: "PROJECT PORTFOLIO",
    subtitle: "Full-stack projects & case studies",
    cta: "OPEN APP",
    sourceCta: "GITHUB",
    galleryCta: "VIEW PHOTO GALLERY",
    prev: "Previous",
    next: "Next",
    close: "Close",
    galleryLabel: "Photo",
    featuredLabel: "⭐ FEATURED PROJECT",
    items: [
      {
        title: "Quote of the Day App (QOTD)",
        desc: "An interactive, responsive daily quote web app that dynamically displays inspiration. Features real-time quote updates, API/data fetching integration, and a modern interface built with Flutter Web for optimal performance across devices (desktop & mobile).",
        tech: [
          "Flutter Web / Dart",
          "Rest API / JSON Integration",
          "HTML5 / CSS3",
          "VS Code",
        ],
        thumb: "/images/quote1.png",
        gallery: [
          "/images/quote1.png",
          "/images/quote2.png",
          "/images/quote3.png",
          "/images/quote4.png",
          "/images/quote5.png",
        ],
        alt: "Quote of the Day App (QOTD) screenshot",
        url: "https://quote-day.netlify.app",
        repo: "https://github.com/nikellaa08/QuoteOfTheDay-Kayla.git",
        featured: true,
        noLinks: false,
      },
      {
        title: "Interactive Quiz",
        desc: "An educational web quiz app based on interactive logic with real-time scoring, streak gamification, real-time remedial mechanics, and educational material explanations wrapped in an elegant frosted glassmorphism UI.",
        tech: ["Flutter Web / Dart", "PHP", "JavaScript", "MySQL", "Glassmorphism UI"],
        thumb: "/images/kuis1.png",
        gallery: [
          "/images/kuis1.png",
          "/images/kuis2.png",
          "/images/kuis3.png",
          "/images/kuis4.png",
          "/images/kuis5.png",
          "/images/kuis6.png",
          "/images/kuis7.png",
          "/images/kuis8.png",
        ],
        alt: "Interactive Quiz app screenshot",
        url: "https://kuis-intrktf.netlify.app",
        repo: "https://github.com/nikellaa08/Kuis-Kayla.git",
        featured: true,
        noLinks: false,
      },
      {
        title: "Student Attendance System",
        desc: "A web-based student attendance website designed to help schools manage and monitor student presence digitally. The system features Admin/Teacher and Student roles, one-click manual attendance with lateness detection, permission and sick leave requests with supporting document uploads, teacher verification, attendance history, and an attendance monitoring dashboard.",
        tech: [
          "Next.js",
          "React",
          "Node.js",
          "Tailwind CSS",
          "Local Storage",
          "FileReader API",
        ],
        thumb: "/images/absen1.png",
        gallery: [
          "/images/absen1.png",
          "/images/absen2.png",
          "/images/absen3.png",
          "/images/absen4.png",
          "/images/absen5.png",
        ],
        alt: "Student Attendance System screenshot",
        url: "https://symphonious-basbousa-5b7956.netlify.app/",
        repo: "https://github.com/nikellaa08/AbsensiSiswa-Kayla.git",
        featured: false,
        noLinks: false,
      },
      {
        title: "Relawan Nusantara",
        desc: "An interactive volunteer coordination web platform designed to streamline registration, scheduling, and management of social, environmental, and educational activities in one integrated system.",
        tech: ["Node.js", "Express", "JavaScript", "MySQL"],
        thumb: "/images/relawan.png",
        gallery: ["/images/relawan.png"],
        alt: "Relawan Nusantara platform screenshot",
        url: "",
        repo: "",
        featured: false,
        noLinks: true,
      },
    ],
  },
  experience: {
    kicker: "02 // EXP LOG",
    title: "ADVENTURE LOG",
    subtitle: "Experience & track record",
    entries: [
      {
        tag: "Lv. 1 — EDUCATION",
        color: "yellow",
        title: "Education",
        desc: "",
        schools: [
          {
            name: "SMK Jakarta Pusat 1 (Vocational HS)",
            period: "2024 – 2027",
            detail: "Software Engineering (RPL)",
          },
        ],
      },
      {
        tag: "Lv. 2 — PROJECT DEV",
        color: "blue",
        title: "Web & App Development Experience",
        desc: "Hands-on experience designing, building, and refining interactive web applications based on full-stack logic and modern interfaces.",
        subs: [
          {
            name: "Lead Developer — Quote of the Day App (QOTD)",
            desc: "Built an interactive daily quote web app with Flutter Web featuring real-time updates and API data fetching.",
          },
          {
            name: "Lead Developer — Interactive Quiz",
            desc: "Designed an educational quiz app with PHP, JavaScript, and MySQL logic, a frosted glassmorphism UI, and real-time scoring.",
          },
          {
            name: "Full-Stack Developer — Student Attendance System",
            desc: "Built a digital attendance management system with Next.js App Router and Tailwind CSS, featuring teacher verification, lateness detection, and a monitoring dashboard.",
          },
          {
            name: "Full-Stack Developer (Team Collaboration) — Relawan Nusantara",
            desc: "Built an interactive volunteer coordination web platform for social, environmental, and educational activities using Node.js, Express, JavaScript, and MySQL.",
          },
        ],
      },
      {
        tag: "Lv. 3 — ORGANIZATION",
        color: "green",
        title: "Organizational Activities & Extracurriculars",
        desc: "Active involvement in various non-academic activities that build teamwork and technical skills.",
        subs: [
          {
            name: "Broadcasting",
            desc: "Training in professional photo and video camera-angle techniques.",
          },
          {
            name: "Theater, Hadroh, & Choir",
            desc: "Sharpening team harmony, work rhythm, and member coordination in public performances.",
          },
        ],
      },
    ],
  },
  resume: {
    kicker: "RESUME",
    title: "PROFESSIONAL RESUME",
    subtitle: "CV preview & official document",
    viewOnline: "VIEW ONLINE",
    download: "DOWNLOAD PDF",
    previewLabel: "RESUME PREVIEW",
    pdfHint: "PDF",
    previewFallback:
      "Preview may not render on some devices — use the 👁 VIEW ONLINE button to open it in your browser.",
    backLabel: "BACK TO HOME",
  },
  contact: {
    kicker: "04 // CONTACT",
    title: "LET'S CONNECT",
    subtitle: "Ready to start a new quest with you",
    note: "⚡ Fast response — usually within 24 hours.",
    items: [
      {
        label: "EMAIL",
        value: "nikellaa08@gmail.com",
        href: "mailto:nikellaa08@gmail.com",
        emoji: "✉️",
        color: "yellow",
      },
      {
        label: "LINKEDIN",
        value: "linkedin.com/in/kayla-l-8b276b424",
        href: "https://www.linkedin.com/in/kayla-l-8b276b424",
        emoji: "💼",
        color: "blue",
      },
      {
        label: "WHATSAPP",
        value: "+62 857-7122-0340",
        href: "https://wa.me/6285771220340",
        emoji: "💬",
        color: "green",
      },
      {
        label: "GITHUB",
        value: "@nikellaa08",
        href: "https://github.com/nikellaa08",
        emoji: "🐙",
        color: "ink",
      },
    ],
    cvCta: "VIEW RESUME",
    emailCta: "or email me directly",
  },
  footer: {
    text: "© 2026 Ratu Habibilah. Built with Next.js & Tailwind CSS.",
  },
};

export const content: Record<Lang, Content> = { id: idContent, en: enContent };
